# Generated by Django 4.1.7 on 2023-03-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TVParser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_url', models.CharField(max_length=100)),
                ('title_text', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('country_genre_diroctor', models.TextField()),
                ('actors', models.CharField(max_length=100)),
            ],
        ),
    ]
