# Generated by Django 4.1.7 on 2023-03-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvparser',
            name='original_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
