# Generated by Django 4.1.7 on 2023-03-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0002_tvparser_original_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvparser',
            name='country_genre_diroctor',
        ),
        migrations.AddField(
            model_name='tvparser',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
