# Generated by Django 4.1.7 on 2023-03-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0004_rename_tvparser_kinopoiskparser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGParser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_url', models.CharField(max_length=100)),
                ('title_text', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('rating', models.IntegerField(null=True)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='KinopoiskParser',
        ),
    ]
