# Generated by Django 4.1.7 on 2023-03-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0005_pgparser_delete_kinopoiskparser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgparser',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
